model: 
  model_type: free_space_magnetic
  location_scaling: 1.0 #1.0e+3       # this tells us how to scale dipole location step, maybe set up a different setting for optimization routine
  moment_scaling: 1.0
  radius: 0.091 

mesh: 
  mesh_type: tunneling
  xroi: [-15, 15]
  yroi: [1,30]
  zroi: [-5, 5]                   
  num_x: 31 #61
  num_y: 30 #60 
  num_z: 11 #21

data:
  rms_noise: 0.5e-12                # setting low noise 0.5pT/sqrt(Hz) * sqrt(10 Hz) 
  moment_magnitude: 30               # we want field strenth of 5nT at 5 meters. We get this with 30 Am^2. 
  moment_orientation: random            # set to tangential (typical for sphere) or random (free space)

sensors:
  array_type: external       
  num_sensors: 8
  bias_field: [0,2.5e-5,-4.33013e-5]    # field points due north 60 degrees into the earth
  gradiometers: False


