model: 
  model_type: conducting_sphere
  radius: 0.816   # not sure if this is correct, with the conducting sphere, we need to choose a radius (does it enter into equation?) 

mesh: 
  mesh_type: cartesian
  xroi: [-0.15,0.15]
  yroi: [0.5,0.8]
  zroi: [-0.15, 0.15]                   
  num_x: 31
  num_y: 31 
  num_z: 31

data:
  rms_noise: 1.58114e-12                # setting low noise 0.5pT/sqrt(Hz) * sqrt(10 Hz) 
  moment_magnitude:                # we want field strenth of 5nT at 5 meters. We get this with 30 Am^2. 
  moment_orientation: random            # set to tangential (typical for sphere) or random (free space)

sensors:
  array_type: phantom       
  num_sensors: 9
  bias_field: radial  # [0,2.5e-5,-4.33013e-5]    # field points due north 60 degrees into the earth
  gradiometers: True


